#!/bin/sh

# Set these paths appropriately

BIN=/home/hizukuri/TreeTagger/bin
CMD=/home/hizukuri/TreeTagger/cmd
LIB=/home/hizukuri/TreeTagger/lib

OPTIONS="-token -lemma -sgml"

TAGGER=${BIN}/tree-tagger
TOKENIZER=${CMD}/utf8-tokenize.perl
PARFILE=${LIB}/slovenian-utf8.par

$TOKENIZER $* |
$TAGGER $OPTIONS $PARFILE
